# Generated by Django 2.2.4 on 2019-08-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='标题')),
                ('slug', models.SlugField(blank=True, max_length=60, verbose_name='slug')),
                ('body', models.TextField(verbose_name='正文')),
                ('pub_date', models.DateTimeField(null=True, verbose_name='发布时间')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
    ]
