# Generated by Django 2.2.4 on 2019-08-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190820_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.CharField(blank=True, max_length=200, verbose_name='博客摘要'),
        ),
    ]
